apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: jithingeorge10/jobclub-auth-service:latest # Replace with your Docker image
          ports:
            - containerPort: 4000 # The port your auth-service listens on
          envFrom:
            - configMapRef:
                name: auth-service-env # Reference to the ConfigMap we'll create
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-srv
spec:
  selector:
    app: auth-service
  ports:
    - name: auth-service-port
      protocol: TCP
      port: 4000
      targetPort: 4000
