apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: jithingeorge10/jobclub-chat-service:latest  # Replace with your Docker image
          ports:
            - containerPort: 4003  # The port your chat-service listens on
          envFrom:
            - configMapRef:
                name: chat-service-env  # Reference to the ConfigMap we'll create
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-srv
spec:
  selector:
    app: chat-service
  ports:
    - name: chat-service-port
      protocol: TCP
      port: 4003
      targetPort: 4003
