apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
    spec:
      containers:
        - name: company-service-container
          image: jithingeorge10/jobclub-company-service:latest
          envFrom:
            - configMapRef:
                name: company-service-env
---
apiVersion: v1
kind: Service
metadata:
  name: company-service-srv
spec:
  selector:
    app: company-service
  ports:
    - name: company-service-ports
      protocol: TCP
      port: 4002
      targetPort: 4002
